import random

list1 = random.sample(range(1,49),7)
print ("The First of mark six number is :")
print (list1[0])
print ("The Second of mark six number is :")
print (list1[1])
print ("The Third of mark six number is :")
print (list1[2])
print ("The Fourth of mark six number is :")
print (list1[3])
print ("The Fifth of mark six number is :")
print (list1[4])
print ("The Sixth of mark six number is :")
print (list1[5])
print ("The special number of mark six number is :")
print (list1[6])
